[package]
name = "mathtutor"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "mt"
path = "src/main.rs"

[dependencies]
argh = "0.1.19"
ayml = "0.1.0"
chrono = { version = "0.4", features = ["serde"] }
fsrs = "5.2.0"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
tracing = "0.1.44"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
